var items = ["Leather Helmet", "Leather Chestplate", "Leather Pants", "Leather Boots", "Gold Helmet", "Gold Chestplate", "Gold Pants", "Gold Boots", "Chainmail Helmet", "Chainmail Chestplate", "Chainmail Pants", "Chainmail Boots", "Iron Helmet", "Iron Chestplate", "Iron Pants", "Iron Boots", "Diamond Helmet", "Diamond Chestplate", "Diamond Pants", "Diamond Boots", "Netherite Helmet", "Netherite Chestplate", "Netherite Pants", "Netherite Boots", "Turtle Helmet", "Elytra","Wooden Sword", "Wooden Axe", "Wooden Pickaxe", "Wooden Shovel", "Wooden Hoe","Golden Sword", "Golden Axe", "Golden Pickaxe", "Golden Shovel", "Golden Hoe","Stone Sword", "Stone Axe", "Stone Pickaxe", "Stone Shovel", "Stone Hoe","Iron Sword", "Iron Axe", "Iron Pickaxe", "Iron Shovel", "Iron Hoe","Diamond Sword", "Diamond Axe", "Diamond Pickaxe", "Diamond Shovel", "Diamond Hoe","Netherite Sword", "Netherite Axe", "Netherite Pickaxe", "Netherite Shovel", "Netherite Hoe","Shield", "Trident", "Totem of Undying", " Flint and steel", "Shears", "Fishing Rod",  "Empty Bucket", "Water Bucket", "Lava Bucket", "Milk Bucket", "End Crystal", "Ender Pearl", "Bottle o' Enchanting", "Respawn Anchor", "Firework Rocket", "Snowball", "Bed","Apple", "Mushroom Stew", "Bread", "Raw Porkchop", "Cooked Porkchop",  "Golden Apple", "Enchanted Golden Apple", "Raw Cod", "Raw Salmon", "Tropical Fish", " Pufferfish", "Cooked Cod", "Cooked Salmon", "Cake", "Cookie", "Melon Slice", "Dried Kelp", "Raw Beef", "Steak", "Raw Chicken", "Cooked Chicken", "Rotten Flesh", " Spider Eye", "Carrot", "Potato", "Baked Potato", "Golden Carrot", "Pumpkin Pie", "Raw Rabbit", "Cooked Rabbit", "Rabbit Stew", "Raw Mutton", "Cooked Mutton", "Chorus Fruit", "Beetroot", "Beetroot Soup", "Suspicious Stewඞ", "Sweet Berries", "Honey Bottle",
"Obsidian", "Anvil", "Block Of Netherite", "Ender Chest", "End Stone", "Cobblestone", "Block Of Redstone", "Block Of Coal", "Block Of Iron", "Block Of Gold", "Block Of Diamond", "Block Of Emerald", "Iron Door", "Cobweb", "Oak Plank", "Block Of Lapis Lazuli", "Oak Door", "Blue Ice", "Crafting Table", "Bone Block", "Oak Log", "Gray Concrete", "Pumpkin", "Melon", "Sandstone", "Note Block", "Wool", "Gravel", "Clay", "Sponge", "Packed Ice", "Magma Block", "Soul Sand", "Hay Bale", "Dirt", "Sand", "Ice", "Netherrack", "Glass", "Glowstone", "Snow Block", "TNT", "Slime Block", "Honey Block", "Scaffolding", "Arrow","Horse Spawn Egg", "Horse Spawn Egg (Leather Armor)", "Horse Spawn Egg(Gold Armor)", "Horse spawn Egg(Iron Armor)", "Horse Spawn Egg(Diamond Armor)", "Mule Spawn Egg", "Sheep Spawn Egg", "Pig Spawn Egg", "Parrot Spawn Egg", "Strider Spawn Egg", "Bucket of pufferfish", "Carrot on a stick", "Warped Fungus On A Stick", "Player Tracker", "Oak Boat"
]

const itemChoise=document.getElementById('items1')
function generate(){

itemChoise.textContent="Your Items Are "+(Math.floor(Math.random()*64)+1)+' '+items[Math.floor(Math.random()*items.length)]+'(s) and '+(Math.floor(Math.random()*64)+1)+' '+items[Math.floor(Math.random()*items.length)]

}